// Generated from local MegaMek MTF records; see tools/export-supported-critical-layouts.mjs.
const BT_CRITICAL_LAYOUTS = Object.freeze({
  "atlas-as7-d": {
    "la": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "Hand Actuator",
      "Heat Sink",
      "Medium Laser",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ra": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "Hand Actuator",
      "Heat Sink",
      "Medium Laser",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "lt": [
      "Heat Sink",
      "LRM 20",
      "LRM 20",
      "LRM 20",
      "LRM 20",
      "LRM 20",
      "SRM 6",
      "SRM 6",
      "IS Ammo LRM-20",
      "IS Ammo LRM-20",
      "IS Ammo SRM-6",
      null
    ],
    "rt": [
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "IS Ammo AC/20",
      "IS Ammo AC/20"
    ],
    "ct": [
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Gyro",
      "Gyro",
      "Gyro",
      "Gyro",
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Medium Laser (R)",
      "Medium Laser (R)"
    ],
    "head": [
      "Life Support",
      "Sensors",
      "Cockpit",
      "Heat Sink",
      "Sensors",
      "Life Support",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ll": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Heat Sink",
      "Heat Sink",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rl": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Heat Sink",
      "Heat Sink",
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "hunchback-hbk-4g": {
    "la": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "Hand Actuator",
      "Medium Laser",
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ra": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "Hand Actuator",
      "Medium Laser",
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "lt": [
      "IS Ammo AC/20",
      "IS Ammo AC/20",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rt": [
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      "Autocannon/20",
      null,
      null
    ],
    "ct": [
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Gyro",
      "Gyro",
      "Gyro",
      "Gyro",
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Heat Sink",
      null
    ],
    "head": [
      "Life Support",
      "Sensors",
      "Cockpit",
      "Small Laser",
      "Sensors",
      "Life Support",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ll": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Heat Sink",
      "Heat Sink",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rl": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Heat Sink",
      "Heat Sink",
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "locust-lct-1v": {
    "la": [
      "Shoulder",
      "Upper Arm Actuator",
      "Machine Gun",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ra": [
      "Shoulder",
      "Upper Arm Actuator",
      "Machine Gun",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "lt": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rt": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ct": [
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Gyro",
      "Gyro",
      "Gyro",
      "Gyro",
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Medium Laser",
      "IS Ammo MG - Full"
    ],
    "head": [
      "Life Support",
      "Sensors",
      "Cockpit",
      null,
      "Sensors",
      "Life Support",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ll": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Heat Sink",
      "Heat Sink",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rl": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Heat Sink",
      "Heat Sink",
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "marauder-mad-3r": {
    "la": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "PPC",
      "PPC",
      "PPC",
      "Medium Laser",
      null,
      null,
      null,
      null,
      null
    ],
    "ra": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "PPC",
      "PPC",
      "PPC",
      "Medium Laser",
      null,
      null,
      null,
      null,
      null
    ],
    "lt": [
      "IS Ammo AC/5",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rt": [
      "Autocannon/5",
      "Autocannon/5",
      "Autocannon/5",
      "Autocannon/5",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ct": [
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Gyro",
      "Gyro",
      "Gyro",
      "Gyro",
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      null,
      null
    ],
    "head": [
      "Life Support",
      "Sensors",
      "Cockpit",
      null,
      "Sensors",
      "Life Support",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ll": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Heat Sink",
      "Heat Sink",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rl": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Heat Sink",
      "Heat Sink",
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "enforcer-enf-4r": {
    "la": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "Large Laser",
      "Large Laser",
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ra": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      null,
      null
    ],
    "lt": [
      "Heat Sink",
      "Heat Sink",
      "Small Laser",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rt": [
      "Heat Sink",
      "Heat Sink",
      "IS Ammo AC/10",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ct": [
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Gyro",
      "Gyro",
      "Gyro",
      "Gyro",
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      null,
      null
    ],
    "head": [
      "Life Support",
      "Sensors",
      "Cockpit",
      null,
      "Sensors",
      "Life Support",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ll": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Jump Jet",
      "Jump Jet",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rl": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      "Jump Jet",
      "Jump Jet",
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "centurion-cn9-a": {
    "la": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "Hand Actuator",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ra": [
      "Shoulder",
      "Upper Arm Actuator",
      "Lower Arm Actuator",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      "Autocannon/10",
      null,
      null
    ],
    "lt": [
      "Heat Sink",
      "LRM 10",
      "LRM 10",
      "IS Ammo LRM-10",
      "IS Ammo LRM-10",
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rt": [
      "Heat Sink",
      "IS Ammo AC/10",
      "IS Ammo AC/10",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ct": [
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Gyro",
      "Gyro",
      "Gyro",
      "Gyro",
      "Fusion Engine",
      "Fusion Engine",
      "Fusion Engine",
      "Medium Laser",
      "Medium Laser (R)"
    ],
    "head": [
      "Life Support",
      "Sensors",
      "Cockpit",
      null,
      "Sensors",
      "Life Support",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "ll": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "rl": [
      "Hip",
      "Upper Leg Actuator",
      "Lower Leg Actuator",
      "Foot Actuator",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  }
});
