-- Retained as an intentionally safe compatibility waypoint. The former
-- version attempted to edit the installed resolver's source text and could
-- fail when a live database had a different legitimate revision. SQL/51 now
-- installs both maintained resolvers directly and includes this functionality.
