-- Server-authoritative Charge attacks. Run after SQL/57.

CREATE OR REPLACE FUNCTION public.declare_charge_attack(
 p_game_id uuid,p_attacker_instance_id text,p_target_instance_id text,p_staging_col int,p_staging_row int,p_staging_facing int,
 p_mode text,p_hexes_moved int,p_mp_used int
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE g btech_games%ROWTYPE;player btech_players%ROWTYPE;st jsonb;units jsonb;attacker jsonb;target jsonb;definition jsonb;mp_max int;heat_penalty int;movement_heat int;direction int;source_level int;target_level int;
BEGIN
 IF p_mode NOT IN ('walk','run') OR p_hexes_moved<1 OR p_mp_used<1 THEN RAISE EXCEPTION 'A Charge requires forward walking or running movement';END IF;
 IF p_staging_col NOT BETWEEN 0 AND 15 OR p_staging_row NOT BETWEEN 0 AND 11 OR p_staging_facing NOT BETWEEN 0 AND 5 THEN RAISE EXCEPTION 'Charge staging position is outside the battlefield';END IF;
 SELECT * INTO g FROM btech_games WHERE id=p_game_id FOR UPDATE;SELECT * INTO player FROM btech_players WHERE game_id=p_game_id AND user_id=auth.uid() AND role='player';
 IF NOT FOUND OR g.status<>'in-progress' OR g.current_phase<>'movement' OR g.active_player_id IS DISTINCT FROM player.id THEN RAISE EXCEPTION 'It is not your Movement activation';END IF;
 st:=CASE jsonb_typeof(g.state) WHEN 'string' THEN (g.state#>>'{}')::jsonb ELSE g.state END;
 SELECT value INTO attacker FROM jsonb_array_elements(st->'mech_instances') value WHERE value->>'instanceId'=p_attacker_instance_id;SELECT value INTO target FROM jsonb_array_elements(st->'mech_instances') value WHERE value->>'instanceId'=p_target_instance_id;
 IF attacker IS NULL OR (attacker->>'owner')::int<>player.seat_number OR coalesce((attacker->>'hasMoved')::boolean,false) OR coalesce((attacker->>'destroyed')::boolean,false) OR coalesce((attacker->>'prone')::boolean,false) OR coalesce((attacker->>'shutdown')::boolean,false) OR coalesce(attacker->'pilot'->>'consciousness','conscious')<>'conscious' THEN RAISE EXCEPTION 'Attacker is not eligible to Charge';END IF;
 IF target IS NULL OR (target->>'owner')::int=(attacker->>'owner')::int OR NOT coalesce((target->>'hasMoved')::boolean,false) OR coalesce((target->>'destroyed')::boolean,false) OR coalesce((target->>'prone')::boolean,false) OR target ? 'dfaDeclaration' OR target ? 'chargeDeclaration' THEN RAISE EXCEPTION 'Choose a standing enemy that has completed movement and is not making a displacement attack';END IF;
 IF btech_hex_distance(p_staging_col,p_staging_row,(target->>'col')::int,(target->>'row')::int)<>1 THEN RAISE EXCEPTION 'Charge staging hex must be one hex short of the target';END IF;
 direction:=btech_direction_to(p_staging_col,p_staging_row,(target->>'col')::int,(target->>'row')::int);IF p_staging_facing<>direction THEN RAISE EXCEPTION 'A charging BattleMech must face the target';END IF;
 IF EXISTS (SELECT 1 FROM jsonb_array_elements(st->'mech_instances') unit WHERE unit->>'instanceId'<>p_attacker_instance_id AND (unit->>'col')::int=p_staging_col AND (unit->>'row')::int=p_staging_row AND NOT coalesce((unit->>'destroyed')::boolean,false)) THEN RAISE EXCEPTION 'Charge staging hex is occupied';END IF;
 SELECT definition INTO definition FROM btech_catalogue_units WHERE catalogue_version=g.catalogue_version AND unit_id=attacker->>'unitId';heat_penalty:=CASE WHEN coalesce((attacker->>'roundStartingHeat')::int,coalesce((attacker->>'heat')::int,0))>=25 THEN 4 WHEN coalesce((attacker->>'roundStartingHeat')::int,coalesce((attacker->>'heat')::int,0))>=20 THEN 3 WHEN coalesce((attacker->>'roundStartingHeat')::int,coalesce((attacker->>'heat')::int,0))>=15 THEN 2 WHEN coalesce((attacker->>'roundStartingHeat')::int,coalesce((attacker->>'heat')::int,0))>=10 THEN 1 ELSE 0 END;mp_max:=greatest(0,coalesce((definition->'movement'->>p_mode)::int,0)-heat_penalty);
 IF p_mp_used>mp_max OR p_hexes_moved>mp_max OR btech_hex_distance((attacker->>'col')::int,(attacker->>'row')::int,p_staging_col,p_staging_row)>mp_max THEN RAISE EXCEPTION 'Charge movement exceeds available Movement Points';END IF;
 source_level:=btech_elevation(coalesce(st->>'map_id','training-grounds'),lpad(p_staging_col::text,2,'0')||lpad(p_staging_row::text,2,'0'));target_level:=btech_elevation(coalesce(st->>'map_id','training-grounds'),lpad(target->>'col',2,'0')||lpad(target->>'row',2,'0'));IF abs(source_level-target_level)>1 THEN RAISE EXCEPTION 'Charge target must be within one elevation level';END IF;
 movement_heat:=CASE p_mode WHEN 'run' THEN 2 ELSE 1 END;attacker:=jsonb_set(attacker,'{col}',to_jsonb(p_staging_col),true);attacker:=jsonb_set(attacker,'{row}',to_jsonb(p_staging_row),true);attacker:=jsonb_set(attacker,'{facing}',to_jsonb(p_staging_facing),true);attacker:=jsonb_set(attacker,'{torsoFacing}',to_jsonb(p_staging_facing),true);attacker:=jsonb_set(attacker,'{movementMode}',to_jsonb(p_mode),true);attacker:=jsonb_set(attacker,'{mpUsed}',to_jsonb(p_mp_used),true);attacker:=jsonb_set(attacker,'{hexesMoved}',to_jsonb(p_hexes_moved),true);attacker:=jsonb_set(attacker,'{hasMoved}','true'::jsonb,true);attacker:=jsonb_set(attacker,'{movementHeat}',to_jsonb(movement_heat),true);
 attacker:=jsonb_set(attacker,'{chargeDeclaration}',jsonb_build_object('target_instance_id',p_target_instance_id,'target_col',(target->>'col')::int,'target_row',(target->>'row')::int,'staging_col',p_staging_col,'staging_row',p_staging_row,'hexes_moved',p_hexes_moved,'mode',p_mode),true);
 SELECT jsonb_agg(CASE WHEN value->>'instanceId'=p_attacker_instance_id THEN attacker ELSE value END) INTO units FROM jsonb_array_elements(st->'mech_instances') value;PERFORM submit_phase_state_nonphysical_core(p_game_id,units);RETURN jsonb_build_object('status','declared','target_instance_id',p_target_instance_id,'hexes_moved',p_hexes_moved);
END $$;
REVOKE ALL ON FUNCTION public.declare_charge_attack(uuid,text,text,int,int,int,text,int,int) FROM PUBLIC;GRANT EXECUTE ON FUNCTION public.declare_charge_attack(uuid,text,text,int,int,int,text,int,int) TO authenticated;

DO $$ DECLARE fn regprocedure;source text;patched text;BEGIN
 fn:=to_regprocedure('public.btech_process_weapon_declaration(text,integer,jsonb,text,text,text[],jsonb,boolean)');SELECT pg_get_functiondef(fn) INTO source;IF position('chargeDeclaration' IN source)>0 THEN RETURN;END IF;
 patched:=replace(source,E'IF attacker_start ? ''dfaDeclaration'' AND coalesce(array_length(p_weapon_mounts,1),0)>0',E'IF (attacker_start ? ''dfaDeclaration'' OR attacker_start ? ''chargeDeclaration'') AND coalesce(array_length(p_weapon_mounts,1),0)>0');patched:=replace(patched,E'A BattleMech executing Death From Above cannot fire weapons',E'A BattleMech executing a displacement attack cannot fire weapons');IF patched=source THEN RAISE EXCEPTION 'Could not add Charge weapon restriction';END IF;EXECUTE patched;
END $$;

DO $$ DECLARE fn regprocedure;source text;patched text;BEGIN
 fn:=to_regprocedure('public.btech_resolve_physical_piloting_checks(uuid,text,integer,jsonb)');SELECT pg_get_functiondef(fn) INTO source;IF position('charge_attack' IN source)>0 THEN RETURN;END IF;
 patched:=replace(source,E'IF attack->>''attack_type''=''death_from_above'' THEN CONTINUE;END IF;',E'IF attack->>''attack_type'' IN (''death_from_above'',''charge_attack'') THEN CONTINUE;END IF;');IF patched=source THEN RAISE EXCEPTION 'Could not isolate Charge piloting checks';END IF;EXECUTE patched;
END $$;

CREATE OR REPLACE FUNCTION public.resolve_declared_charge(p_game_id uuid,p_attacker_instance_id text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE g btech_games%ROWTYPE;player btech_players%ROWTYPE;st jsonb;units jsonb;attacker jsonb;target jsonb;decl jsonb;att_mass int;tgt_mass int;att_p int;tgt_p int;target_mod int;tn int;da int;db int;hit boolean;target_damage int:=0;self_damage int:=0;remaining int;group_damage int;loc jsonb;damage_result jsonb;target_groups jsonb:='[]';self_groups jsonb:='[]';direction int;dest jsonb;dest_col int;dest_row int;att_psr jsonb;tgt_psr jsonb;psr_da int;psr_db int;passed boolean;fall_damage int;fall_groups jsonb:='[]';submission jsonb;sequence_no int;event_id uuid;result jsonb;
BEGIN
 SELECT * INTO g FROM btech_games WHERE id=p_game_id FOR UPDATE;SELECT * INTO player FROM btech_players WHERE game_id=p_game_id AND user_id=auth.uid() AND role='player';IF NOT FOUND OR g.current_phase<>'physical_attack' OR g.active_player_id IS DISTINCT FROM player.id THEN RAISE EXCEPTION 'It is not your Physical Attack activation';END IF;
 st:=CASE jsonb_typeof(g.state) WHEN 'string' THEN (g.state#>>'{}')::jsonb ELSE g.state END;SELECT value INTO attacker FROM jsonb_array_elements(st->'mech_instances') value WHERE value->>'instanceId'=p_attacker_instance_id;decl:=attacker->'chargeDeclaration';IF attacker IS NULL OR (attacker->>'owner')::int<>player.seat_number OR decl IS NULL THEN RAISE EXCEPTION 'This BattleMech has no unresolved Charge';END IF;SELECT value INTO target FROM jsonb_array_elements(st->'mech_instances') value WHERE value->>'instanceId'=decl->>'target_instance_id';
 IF target IS NULL OR coalesce((target->>'destroyed')::boolean,false) THEN attacker:=jsonb_set(attacker,'{col}',decl->'target_col',true);attacker:=jsonb_set(attacker,'{row}',decl->'target_row',true);attacker:=attacker-'chargeDeclaration';SELECT jsonb_agg(CASE WHEN value->>'instanceId'=p_attacker_instance_id THEN attacker ELSE value END) INTO units FROM jsonb_array_elements(st->'mech_instances') value;st:=jsonb_set(st,'{mech_instances}',units,true);UPDATE btech_games SET state=st WHERE id=p_game_id;SELECT submit_simultaneous_physical_declaration(p_game_id,p_attacker_instance_id,NULL,'pass',ARRAY[]::text[]) INTO submission;RETURN jsonb_build_object('status','target_destroyed','submission',submission);END IF;
 SELECT (definition->>'mass')::int INTO att_mass FROM btech_catalogue_units WHERE catalogue_version=g.catalogue_version AND unit_id=attacker->>'unitId';SELECT (definition->>'mass')::int INTO tgt_mass FROM btech_catalogue_units WHERE catalogue_version=g.catalogue_version AND unit_id=target->>'unitId';att_p:=coalesce((attacker->'pilot'->>'piloting')::int,(attacker->>'pilotingSkill')::int,5);tgt_p:=coalesce((target->'pilot'->>'piloting')::int,(target->>'pilotingSkill')::int,5);target_mod:=CASE WHEN coalesce((target->>'hexesMoved')::int,0)>=7 THEN 3 WHEN coalesce((target->>'hexesMoved')::int,0)>=5 THEN 2 WHEN coalesce((target->>'hexesMoved')::int,0)>=3 THEN 1 ELSE 0 END;tn:=att_p+(att_p-tgt_p)+CASE decl->>'mode' WHEN 'run' THEN 2 ELSE 1 END+target_mod;da:=floor(random()*6+1);db:=floor(random()*6+1);hit:=tn<=12 AND da+db>=tn;
 IF hit THEN target_damage:=ceil(att_mass/10.0*coalesce((decl->>'hexes_moved')::int,1))::int;self_damage:=ceil(tgt_mass/10.0)::int;remaining:=target_damage;WHILE remaining>0 AND NOT coalesce((target->>'destroyed')::boolean,false) LOOP group_damage:=least(5,remaining);remaining:=remaining-group_damage;loc:=btech_roll_mech_hit_location('front');damage_result:=btech_apply_direct_damage(target,group_damage,loc->>'location',false);target:=damage_result->'mech';target_groups:=target_groups||jsonb_build_array(jsonb_build_object('damage',group_damage,'location',loc->>'location','critical_checks',damage_result->'critical_checks'));END LOOP;remaining:=self_damage;WHILE remaining>0 AND NOT coalesce((attacker->>'destroyed')::boolean,false) LOOP group_damage:=least(5,remaining);remaining:=remaining-group_damage;loc:=btech_roll_mech_hit_location('front');damage_result:=btech_apply_direct_damage(attacker,group_damage,loc->>'location',false);attacker:=damage_result->'mech';self_groups:=self_groups||jsonb_build_array(jsonb_build_object('damage',group_damage,'location',loc->>'location','critical_checks',damage_result->'critical_checks'));END LOOP;
  direction:=btech_direction_to((attacker->>'col')::int,(attacker->>'row')::int,(target->>'col')::int,(target->>'row')::int);dest:=btech_neighbor_hex((target->>'col')::int,(target->>'row')::int,direction);dest_col:=(dest->>'col')::int;dest_row:=(dest->>'row')::int;IF dest_col BETWEEN 0 AND 15 AND dest_row BETWEEN 0 AND 11 AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements(st->'mech_instances') unit WHERE unit->>'instanceId' NOT IN (p_attacker_instance_id,target->>'instanceId') AND (unit->>'col')::int=dest_col AND (unit->>'row')::int=dest_row AND NOT coalesce((unit->>'destroyed')::boolean,false)) THEN target:=jsonb_set(target,'{col}',to_jsonb(dest_col),true);target:=jsonb_set(target,'{row}',to_jsonb(dest_row),true);attacker:=jsonb_set(attacker,'{col}',decl->'target_col',true);attacker:=jsonb_set(attacker,'{row}',decl->'target_row',true);END IF;
  psr_da:=floor(random()*6+1);psr_db:=floor(random()*6+1);passed:=psr_da+psr_db>=att_p+2;att_psr:=jsonb_build_object('target',att_p+2,'die_a',psr_da,'die_b',psr_db,'total',psr_da+psr_db,'passed',passed);IF NOT passed THEN attacker:=jsonb_set(attacker,'{prone}','true'::jsonb,true);fall_damage:=ceil(att_mass/10.0)::int;remaining:=fall_damage;WHILE remaining>0 AND NOT coalesce((attacker->>'destroyed')::boolean,false) LOOP group_damage:=least(5,remaining);remaining:=remaining-group_damage;loc:=btech_roll_mech_hit_location('front');damage_result:=btech_apply_direct_damage(attacker,group_damage,loc->>'location',false);attacker:=damage_result->'mech';END LOOP;att_psr:=jsonb_set(att_psr,'{fall_damage}',to_jsonb(fall_damage),true);END IF;psr_da:=floor(random()*6+1);psr_db:=floor(random()*6+1);passed:=psr_da+psr_db>=tgt_p+2;tgt_psr:=jsonb_build_object('target',tgt_p+2,'die_a',psr_da,'die_b',psr_db,'total',psr_da+psr_db,'passed',passed);IF NOT passed THEN target:=jsonb_set(target,'{prone}','true'::jsonb,true);fall_damage:=ceil(tgt_mass/10.0)::int;remaining:=fall_damage;WHILE remaining>0 AND NOT coalesce((target->>'destroyed')::boolean,false) LOOP group_damage:=least(5,remaining);remaining:=remaining-group_damage;loc:=btech_roll_mech_hit_location('front');damage_result:=btech_apply_direct_damage(target,group_damage,loc->>'location',false);target:=damage_result->'mech';END LOOP;tgt_psr:=jsonb_set(tgt_psr,'{fall_damage}',to_jsonb(fall_damage),true);END IF;
 END IF;
 attacker:=attacker-'chargeDeclaration';SELECT jsonb_agg(CASE WHEN value->>'instanceId'=p_attacker_instance_id THEN attacker WHEN value->>'instanceId'=target->>'instanceId' THEN target ELSE value END) INTO units FROM jsonb_array_elements(st->'mech_instances') value;st:=jsonb_set(st,'{mech_instances}',units,true);UPDATE btech_games SET state=st WHERE id=p_game_id;SELECT submit_simultaneous_physical_declaration(p_game_id,p_attacker_instance_id,NULL,'pass',ARRAY[]::text[]) INTO submission;
 result:=jsonb_build_object('attack_type','charge_attack','to_hit',jsonb_build_object('die_a',da,'die_b',db,'total',da+db,'target',tn),'hit',hit,'damage',target_damage,'groups',target_groups,'self_damage',self_damage,'self_groups',self_groups,'attacker_piloting_check',att_psr,'target_piloting_check',tgt_psr);SELECT coalesce(max(sequence),0)+1 INTO sequence_no FROM btech_combat_events WHERE game_id=p_game_id AND round=g.current_round AND phase='physical_attack';INSERT INTO btech_combat_events(game_id,round,phase,sequence,player_id,attacker_instance_id,target_instance_id,declaration,status,resolution,resolved_at) VALUES(p_game_id,g.current_round,'physical_attack',sequence_no,player.id,p_attacker_instance_id,target->>'instanceId',jsonb_build_object('attack_type','charge','declared_phase','movement'),'resolved',jsonb_build_object('results',jsonb_build_array(result),'state_version','authoritative-charge-01'),now()) RETURNING id INTO event_id;RETURN jsonb_build_object('status','resolved','hit',hit,'result',result,'event_id',event_id,'submission',submission);
END $$;
REVOKE ALL ON FUNCTION public.resolve_declared_charge(uuid,text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION public.resolve_declared_charge(uuid,text) TO authenticated;
