-- Server-authoritative Push attacks. Run after SQL/58.
CREATE OR REPLACE FUNCTION public.resolve_push_attack(p_game_id uuid,p_attacker_instance_id text,p_target_instance_id text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE g btech_games%ROWTYPE;player btech_players%ROWTYPE;st jsonb;units jsonb;attacker jsonb;target jsonb;att_p int;tgt_p int;target_mod int;shoulder_mod int;tn int;da int;db int;hit boolean;direction int;dest jsonb;dest_col int;dest_row int;old_target_col int;old_target_row int;moved boolean:=false;psr_da int;psr_db int;psr_target int;psr_passed boolean;target_mass int;fall_damage int:=0;remaining int;group_damage int;loc jsonb;damage_result jsonb;fall_groups jsonb:='[]';submission jsonb;sequence_no int;event_id uuid;result jsonb;
BEGIN
 SELECT * INTO g FROM btech_games WHERE id=p_game_id FOR UPDATE;SELECT * INTO player FROM btech_players WHERE game_id=p_game_id AND user_id=auth.uid() AND role='player';IF NOT FOUND OR g.status<>'in-progress' OR g.current_phase<>'physical_attack' OR g.active_player_id IS DISTINCT FROM player.id THEN RAISE EXCEPTION 'It is not your Physical Attack activation';END IF;
 st:=CASE jsonb_typeof(g.state) WHEN 'string' THEN (g.state#>>'{}')::jsonb ELSE g.state END;SELECT value INTO attacker FROM jsonb_array_elements(st->'mech_instances') value WHERE value->>'instanceId'=p_attacker_instance_id;SELECT value INTO target FROM jsonb_array_elements(st->'mech_instances') value WHERE value->>'instanceId'=p_target_instance_id;
 IF attacker IS NULL OR (attacker->>'owner')::int<>player.seat_number OR coalesce((attacker->>'hasPhysicalAttacked')::boolean,false) OR coalesce((attacker->>'destroyed')::boolean,false) OR coalesce((attacker->>'prone')::boolean,false) THEN RAISE EXCEPTION 'Attacker is not eligible to Push';END IF;
 IF target IS NULL OR (target->>'owner')::int=(attacker->>'owner')::int OR coalesce((target->>'destroyed')::boolean,false) OR coalesce((target->>'prone')::boolean,false) OR target ? 'dfaDeclaration' OR target ? 'chargeDeclaration' THEN RAISE EXCEPTION 'Choose a standing enemy not making a displacement attack';END IF;
 IF btech_hex_distance((attacker->>'col')::int,(attacker->>'row')::int,(target->>'col')::int,(target->>'row')::int)<>1 THEN RAISE EXCEPTION 'Push target must be adjacent';END IF;direction:=btech_direction_to((attacker->>'col')::int,(attacker->>'row')::int,(target->>'col')::int,(target->>'row')::int);IF direction<>(attacker->>'facing')::int THEN RAISE EXCEPTION 'Push target must be directly ahead';END IF;
 IF btech_elevation(coalesce(st->>'map_id','training-grounds'),lpad(attacker->>'col',2,'0')||lpad(attacker->>'row',2,'0'))<>btech_elevation(coalesce(st->>'map_id','training-grounds'),lpad(target->>'col',2,'0')||lpad(target->>'row',2,'0')) THEN RAISE EXCEPTION 'Push requires both BattleMechs at the same level';END IF;
 IF coalesce((attacker->'structure'->>'la')::int,0)<=0 OR coalesce((attacker->'structure'->>'ra')::int,0)<=0 THEN RAISE EXCEPTION 'Both arms are required to Push';END IF;
 IF EXISTS(SELECT 1 FROM btech_combat_events event CROSS JOIN LATERAL jsonb_array_elements_text(coalesce(event.declaration->'weapon_mounts','[]')) chosen(mount_id) JOIN btech_catalogue_mounts mount ON mount.catalogue_version=g.catalogue_version AND mount.unit_id=attacker->>'unitId' AND mount.mount_id=chosen.mount_id WHERE event.game_id=p_game_id AND event.round=g.current_round AND event.phase='weapon_attack' AND event.attacker_instance_id=p_attacker_instance_id AND mount.location IN ('la','ra')) THEN RAISE EXCEPTION 'A BattleMech cannot Push after firing an arm-mounted weapon';END IF;
 SELECT count(*)::int*2 INTO shoulder_mod FROM (VALUES ('la'),('ra')) arm(location) WHERE btech_physical_component_damaged(g.catalogue_version,attacker,arm.location,'Shoulder');att_p:=coalesce((attacker->'pilot'->>'piloting')::int,(attacker->>'pilotingSkill')::int,5);tgt_p:=coalesce((target->'pilot'->>'piloting')::int,(target->>'pilotingSkill')::int,5);target_mod:=CASE WHEN coalesce((target->>'hexesMoved')::int,0)>=7 THEN 3 WHEN coalesce((target->>'hexesMoved')::int,0)>=5 THEN 2 WHEN coalesce((target->>'hexesMoved')::int,0)>=3 THEN 1 ELSE 0 END;tn:=att_p-1+CASE attacker->>'movementMode' WHEN 'run' THEN 2 WHEN 'walk' THEN 1 WHEN 'jump' THEN 3 ELSE 0 END+target_mod+coalesce(shoulder_mod,0);da:=floor(random()*6+1);db:=floor(random()*6+1);hit:=tn<=12 AND da+db>=tn;
 old_target_col:=(target->>'col')::int;old_target_row:=(target->>'row')::int;
 IF hit THEN dest:=btech_neighbor_hex(old_target_col,old_target_row,direction);dest_col:=(dest->>'col')::int;dest_row:=(dest->>'row')::int;IF dest_col BETWEEN 0 AND 15 AND dest_row BETWEEN 0 AND 11 AND btech_terrain(coalesce(st->>'map_id','training-grounds'),lpad(dest_col::text,2,'0')||lpad(dest_row::text,2,'0'))<>'impassable' AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements(st->'mech_instances') unit WHERE unit->>'instanceId' NOT IN (p_attacker_instance_id,p_target_instance_id) AND (unit->>'col')::int=dest_col AND (unit->>'row')::int=dest_row AND NOT coalesce((unit->>'destroyed')::boolean,false)) THEN target:=jsonb_set(target,'{col}',to_jsonb(dest_col),true);target:=jsonb_set(target,'{row}',to_jsonb(dest_row),true);attacker:=jsonb_set(attacker,'{col}',to_jsonb(old_target_col),true);attacker:=jsonb_set(attacker,'{row}',to_jsonb(old_target_row),true);moved:=true;END IF;
  psr_target:=tgt_p;psr_da:=floor(random()*6+1);psr_db:=floor(random()*6+1);psr_passed:=psr_target<=12 AND psr_da+psr_db>=psr_target;IF NOT psr_passed THEN target:=jsonb_set(target,'{prone}','true'::jsonb,true);SELECT (definition->>'mass')::int INTO target_mass FROM btech_catalogue_units WHERE catalogue_version=g.catalogue_version AND unit_id=target->>'unitId';fall_damage:=ceil(coalesce(target_mass,0)/10.0)::int;remaining:=fall_damage;WHILE remaining>0 AND NOT coalesce((target->>'destroyed')::boolean,false) LOOP group_damage:=least(5,remaining);remaining:=remaining-group_damage;loc:=btech_roll_mech_hit_location('front');damage_result:=btech_apply_direct_damage(target,group_damage,loc->>'location',false);target:=damage_result->'mech';fall_groups:=fall_groups||jsonb_build_array(jsonb_build_object('damage',group_damage,'location',loc->>'location','critical_checks',damage_result->'critical_checks','pilot_check',damage_result->'pilot_check'));END LOOP;END IF;
 END IF;
 SELECT jsonb_agg(CASE WHEN value->>'instanceId'=p_attacker_instance_id THEN attacker WHEN value->>'instanceId'=p_target_instance_id THEN target ELSE value END) INTO units FROM jsonb_array_elements(st->'mech_instances') value;st:=jsonb_set(st,'{mech_instances}',units,true);UPDATE btech_games SET state=st WHERE id=p_game_id;SELECT submit_simultaneous_physical_declaration(p_game_id,p_attacker_instance_id,NULL,'pass',ARRAY[]::text[]) INTO submission;
 result:=jsonb_build_object('attack_type','push_attack','to_hit',jsonb_build_object('die_a',da,'die_b',db,'total',da+db,'target',tn),'hit',hit,'displaced',moved,'destination',CASE WHEN moved THEN dest ELSE NULL END,'target_piloting_check',CASE WHEN hit THEN jsonb_build_object('target',psr_target,'die_a',psr_da,'die_b',psr_db,'total',psr_da+psr_db,'passed',psr_passed,'fall_damage',fall_damage,'fall_groups',fall_groups) ELSE NULL END);SELECT coalesce(max(sequence),0)+1 INTO sequence_no FROM btech_combat_events WHERE game_id=p_game_id AND round=g.current_round AND phase='physical_attack';INSERT INTO btech_combat_events(game_id,round,phase,sequence,player_id,attacker_instance_id,target_instance_id,declaration,status,resolution,resolved_at) VALUES(p_game_id,g.current_round,'physical_attack',sequence_no,player.id,p_attacker_instance_id,p_target_instance_id,jsonb_build_object('attack_type','push'),'resolved',jsonb_build_object('results',jsonb_build_array(result),'state_version','authoritative-push-01'),now()) RETURNING id INTO event_id;RETURN jsonb_build_object('status','resolved','hit',hit,'result',result,'event_id',event_id,'submission',submission);
END $$;
REVOKE ALL ON FUNCTION public.resolve_push_attack(uuid,text,text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION public.resolve_push_attack(uuid,text,text) TO authenticated;
