-- Advanced BattleMech construction for MechLab. Run after SQL/77.
-- The browser preview is deliberately repeated here: only this server-side
-- validation can publish a design into a shared match catalogue.

CREATE OR REPLACE FUNCTION public.btech_custom_equipment(p_key text)
RETURNS jsonb LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
 SELECT CASE p_key
  WHEN 'small_laser' THEN '{"name":"Small Laser","weight":0.5,"slots":1,"damage":3,"heat":1,"range":[1,2,3],"label":"Small Laser"}'
  WHEN 'med_laser' THEN '{"name":"Medium Laser","weight":1,"slots":1,"damage":5,"heat":3,"range":[3,6,9],"label":"Medium Laser"}'
  WHEN 'large_laser' THEN '{"name":"Large Laser","weight":5,"slots":2,"damage":8,"heat":8,"range":[5,10,15],"label":"Large Laser"}'
  WHEN 'ppc' THEN '{"name":"PPC","weight":7,"slots":3,"damage":10,"heat":10,"range":[6,12,18],"minimumRange":3,"label":"PPC"}'
  WHEN 'flamer' THEN '{"name":"Flamer","weight":1,"slots":1,"damage":2,"heat":3,"range":[1,2,3],"label":"Flamer"}'
  WHEN 'ac2' THEN '{"name":"Autocannon/2","weight":6,"slots":1,"damage":2,"heat":1,"range":[8,16,24],"minimumRange":4,"ammoType":"ac2","label":"Autocannon/2"}'
  WHEN 'ac5' THEN '{"name":"Autocannon/5","weight":8,"slots":4,"damage":5,"heat":1,"range":[6,12,18],"minimumRange":3,"ammoType":"ac5","label":"Autocannon/5"}'
  WHEN 'ac10' THEN '{"name":"Autocannon/10","weight":12,"slots":7,"damage":10,"heat":3,"range":[5,10,15],"ammoType":"ac10","label":"Autocannon/10"}'
  WHEN 'ac20' THEN '{"name":"Autocannon/20","weight":14,"slots":10,"damage":20,"heat":7,"range":[3,6,9],"ammoType":"ac20","label":"Autocannon/20"}'
  WHEN 'machine_gun' THEN '{"name":"Machine Gun","weight":0.5,"slots":1,"damage":2,"heat":0,"range":[1,2,3],"ammoType":"machine_gun","label":"Machine Gun"}'
  WHEN 'lrm5' THEN '{"name":"LRM 5","weight":2,"slots":1,"damage":5,"heat":2,"range":[7,14,21],"minimumRange":6,"ammoType":"lrm5","clusterSize":5,"damagePerMissile":1,"missileWeapon":true,"label":"LRM 5"}'
  WHEN 'lrm10' THEN '{"name":"LRM 10","weight":5,"slots":2,"damage":10,"heat":4,"range":[7,14,21],"minimumRange":6,"ammoType":"lrm10","clusterSize":10,"damagePerMissile":1,"missileWeapon":true,"label":"LRM 10"}'
  WHEN 'lrm15' THEN '{"name":"LRM 15","weight":7,"slots":3,"damage":15,"heat":5,"range":[7,14,21],"minimumRange":6,"ammoType":"lrm15","clusterSize":15,"damagePerMissile":1,"missileWeapon":true,"label":"LRM 15"}'
  WHEN 'lrm20' THEN '{"name":"LRM 20","weight":10,"slots":5,"damage":20,"heat":6,"range":[7,14,21],"minimumRange":6,"ammoType":"lrm20","clusterSize":20,"damagePerMissile":1,"missileWeapon":true,"label":"LRM 20"}'
  WHEN 'srm2' THEN '{"name":"SRM 2","weight":1,"slots":1,"damage":4,"heat":2,"range":[3,6,9],"ammoType":"srm2","clusterSize":2,"damagePerMissile":2,"missileWeapon":true,"label":"SRM 2"}'
  WHEN 'srm4' THEN '{"name":"SRM 4","weight":2,"slots":1,"damage":8,"heat":3,"range":[3,6,9],"ammoType":"srm4","clusterSize":4,"damagePerMissile":2,"missileWeapon":true,"label":"SRM 4"}'
  WHEN 'srm6' THEN '{"name":"SRM 6","weight":3,"slots":2,"damage":12,"heat":4,"range":[3,6,9],"ammoType":"srm6","clusterSize":6,"damagePerMissile":2,"missileWeapon":true,"label":"SRM 6"}'
  WHEN 'clan_er_small_laser' THEN '{"name":"Clan ER Small Laser","weight":0.5,"slots":1,"damage":3,"heat":2,"range":[2,4,5],"clan":true,"label":"Clan ER Small Laser"}'
  WHEN 'clan_er_medium_laser' THEN '{"name":"Clan ER Medium Laser","weight":1,"slots":1,"damage":5,"heat":5,"range":[4,8,12],"clan":true,"label":"Clan ER Medium Laser"}'
  WHEN 'clan_er_large_laser' THEN '{"name":"Clan ER Large Laser","weight":4,"slots":1,"damage":8,"heat":12,"range":[7,14,19],"clan":true,"label":"Clan ER Large Laser"}'
  WHEN 'clan_er_ppc' THEN '{"name":"Clan ER PPC","weight":6,"slots":2,"damage":10,"heat":15,"range":[7,14,23],"minimumRange":3,"clan":true,"label":"Clan ER PPC"}'
  WHEN 'clan_large_pulse_laser' THEN '{"name":"Clan Large Pulse Laser","weight":6,"slots":2,"damage":10,"heat":10,"range":[3,7,10],"clan":true,"label":"Clan Large Pulse Laser"}'
  WHEN 'lrm5_clan' THEN '{"name":"Clan LRM 5","weight":1,"slots":1,"damage":5,"heat":2,"range":[7,14,21],"minimumRange":6,"ammoType":"cl_lrm5","clusterSize":5,"damagePerMissile":1,"missileWeapon":true,"clan":true,"label":"Clan LRM 5"}'
  WHEN 'lrm10_clan' THEN '{"name":"Clan LRM 10","weight":2.5,"slots":1,"damage":10,"heat":4,"range":[7,14,21],"minimumRange":6,"ammoType":"cl_lrm10","clusterSize":10,"damagePerMissile":1,"missileWeapon":true,"clan":true,"label":"Clan LRM 10"}'
  WHEN 'lrm15_clan' THEN '{"name":"Clan LRM 15","weight":3.5,"slots":1,"damage":15,"heat":5,"range":[7,14,21],"minimumRange":6,"ammoType":"cl_lrm15","clusterSize":15,"damagePerMissile":1,"missileWeapon":true,"clan":true,"label":"Clan LRM 15"}'
  WHEN 'lrm20_clan' THEN '{"name":"Clan LRM 20","weight":5,"slots":1,"damage":20,"heat":6,"range":[7,14,21],"minimumRange":6,"ammoType":"cl_lrm20","clusterSize":20,"damagePerMissile":1,"missileWeapon":true,"clan":true,"label":"Clan LRM 20"}'
  WHEN 'srm2_clan' THEN '{"name":"Clan SRM 2","weight":0.5,"slots":1,"damage":4,"heat":2,"range":[3,6,9],"ammoType":"cl_srm2","clusterSize":2,"damagePerMissile":2,"missileWeapon":true,"clan":true,"label":"Clan SRM 2"}'
  WHEN 'srm4_clan' THEN '{"name":"Clan SRM 4","weight":1,"slots":1,"damage":8,"heat":3,"range":[3,6,9],"ammoType":"cl_srm4","clusterSize":4,"damagePerMissile":2,"missileWeapon":true,"clan":true,"label":"Clan SRM 4"}'
  WHEN 'srm6_clan' THEN '{"name":"Clan SRM 6","weight":1.5,"slots":1,"damage":12,"heat":4,"range":[3,6,9],"ammoType":"cl_srm6","clusterSize":6,"damagePerMissile":2,"missileWeapon":true,"clan":true,"label":"Clan SRM 6"}' END::jsonb
$$;

CREATE OR REPLACE FUNCTION public.btech_custom_ammo(p_type text)
RETURNS jsonb LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
 SELECT CASE p_type
  WHEN 'ac2' THEN '{"name":"IS Ammo AC/2","shots":45}' WHEN 'ac5' THEN '{"name":"IS Ammo AC/5","shots":20}' WHEN 'ac10' THEN '{"name":"IS Ammo AC/10","shots":10}' WHEN 'ac20' THEN '{"name":"IS Ammo AC/20","shots":5}' WHEN 'machine_gun' THEN '{"name":"IS Ammo MG","shots":200}'
  WHEN 'lrm5' THEN '{"name":"IS Ammo LRM-5","shots":24}' WHEN 'lrm10' THEN '{"name":"IS Ammo LRM-10","shots":12}' WHEN 'lrm15' THEN '{"name":"IS Ammo LRM-15","shots":8}' WHEN 'lrm20' THEN '{"name":"IS Ammo LRM-20","shots":6}' WHEN 'srm2' THEN '{"name":"IS Ammo SRM-2","shots":50}' WHEN 'srm4' THEN '{"name":"IS Ammo SRM-4","shots":25}' WHEN 'srm6' THEN '{"name":"IS Ammo SRM-6","shots":15}'
  WHEN 'cl_lrm5' THEN '{"name":"Clan Ammo LRM-5","shots":24,"clan":true}' WHEN 'cl_lrm10' THEN '{"name":"Clan Ammo LRM-10","shots":12,"clan":true}' WHEN 'cl_lrm15' THEN '{"name":"Clan Ammo LRM-15","shots":8,"clan":true}' WHEN 'cl_lrm20' THEN '{"name":"Clan Ammo LRM-20","shots":6,"clan":true}' WHEN 'cl_srm2' THEN '{"name":"Clan Ammo SRM-2","shots":50,"clan":true}' WHEN 'cl_srm4' THEN '{"name":"Clan Ammo SRM-4","shots":25,"clan":true}' WHEN 'cl_srm6' THEN '{"name":"Clan Ammo SRM-6","shots":15,"clan":true}' END::jsonb
$$;

CREATE OR REPLACE FUNCTION public.btech_build_custom_layout(p_design jsonb)
RETURNS jsonb LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE layout jsonb:='{"head":["Life Support","Sensors","Cockpit",null,"Sensors","Life Support",null,null,null,null,null,null],"ct":["Fusion Engine","Fusion Engine","Fusion Engine","Gyro","Gyro","Gyro","Gyro","Fusion Engine","Fusion Engine","Fusion Engine",null,null],"lt":[null,null,null,null,null,null,null,null,null,null,null,null],"rt":[null,null,null,null,null,null,null,null,null,null,null,null],"la":["Shoulder","Upper Arm Actuator","Lower Arm Actuator","Hand Actuator",null,null,null,null,null,null,null,null],"ra":["Shoulder","Upper Arm Actuator","Lower Arm Actuator","Hand Actuator",null,null,null,null,null,null,null,null],"ll":["Hip","Upper Leg Actuator","Lower Leg Actuator","Foot Actuator",null,null,null,null,null,null,null,null],"rl":["Hip","Upper Leg Actuator","Lower Leg Actuator","Foot Actuator",null,null,null,null,null,null,null,null]}'::jsonb;
 item jsonb;profile jsonb;bins int;counter int;rating int:=(p_design->>'tonnage')::int*(p_design->>'walking_mp')::int;external_sinks int;engine_slots int:=CASE p_design->>'engine_type' WHEN 'is_xl' THEN 3 WHEN 'clan_xl' THEN 2 ELSE 0 END;endo_slots int:=CASE p_design->>'structure_type' WHEN 'is_endo_steel' THEN 14 WHEN 'clan_endo_steel' THEN 7 ELSE 0 END;ferro_slots int:=CASE p_design->>'armor_type' WHEN 'is_ferro_fibrous' THEN 14 WHEN 'clan_ferro_fibrous' THEN 7 ELSE 0 END;
BEGIN
 FOR counter IN 1..engine_slots LOOP layout:=btech_custom_allocate_slots(layout,'lt','Fusion Engine',1);layout:=btech_custom_allocate_slots(layout,'rt','Fusion Engine',1);END LOOP;
 FOR counter IN 1..endo_slots LOOP layout:=btech_custom_allocate_any(layout,'Endo Steel',ARRAY['lt','rt','la','ra','ll','rl','ct','head']);END LOOP;
 FOR counter IN 1..ferro_slots LOOP layout:=btech_custom_allocate_any(layout,'Ferro-Fibrous Armour',ARRAY['lt','rt','la','ra','ll','rl','ct','head']);END LOOP;
 FOR item IN SELECT value FROM jsonb_array_elements(p_design->'weapons') value LOOP profile:=btech_custom_equipment(item->>'key');layout:=btech_custom_allocate_slots(layout,item->>'location',profile->>'label',(profile->>'slots')::int);END LOOP;
 FOR item IN SELECT value FROM jsonb_array_elements(p_design->'ammo') value LOOP bins:=(item->>'bins')::int;FOR counter IN 1..bins LOOP layout:=btech_custom_allocate_slots(layout,item->>'location',btech_custom_ammo(item->>'type')->>'name',1);END LOOP;END LOOP;
 FOR counter IN 1..(p_design->>'jump_mp')::int LOOP layout:=btech_custom_allocate_any(layout,'Jump Jet',ARRAY['ll','rl','lt','rt','ct']);END LOOP;
 external_sinks:=greatest(0,(p_design->>'heat_sinks')::int-least(10,floor(rating/25.0)::int));FOR counter IN 1..external_sinks LOOP layout:=btech_custom_allocate_any(layout,'Heat Sink',ARRAY['lt','rt','la','ra','ll','rl','ct','head']);END LOOP;RETURN layout;
END $$;

CREATE OR REPLACE FUNCTION public.btech_validate_custom_design(p_design jsonb)
RETURNS jsonb LANGUAGE plpgsql STABLE SET search_path=public AS $$
DECLARE tonnage int;walking int;jumping int;sinks int;rating int;structure jsonb;armor jsonb;weapons jsonb;ammo jsonb;item jsonb;profile jsonb;ammo_profile jsonb;tech_base text;engine_type text;structure_type text;armor_type text;structure_weight numeric;engine_weight numeric;gyro_weight numeric;armor_points int:=0;armor_weight numeric;equipment_weight numeric:=0;ammo_weight numeric:=0;sink_weight numeric;jump_weight numeric;total_weight numeric;layout jsonb;loc text;value_int int;engine_multiplier numeric:=1;structure_multiplier numeric:=1;armor_points_per_ton numeric:=16;
BEGIN
 IF jsonb_typeof(p_design)<>'object' OR length(btrim(coalesce(p_design->>'name',''))) NOT BETWEEN 1 AND 48 OR length(btrim(coalesce(p_design->>'variant',''))) NOT BETWEEN 1 AND 24 THEN RAISE EXCEPTION 'Enter a chassis name and variant';END IF;
 IF btrim(p_design->>'name') !~ '^[A-Za-z0-9][A-Za-z0-9 ._''/-]*$' OR btrim(p_design->>'variant') !~ '^[A-Za-z0-9][A-Za-z0-9 ._''/-]*$' THEN RAISE EXCEPTION 'Names may use letters, numbers, spaces and simple punctuation only';END IF;
 tech_base:=CASE coalesce(p_design->>'tech_base','IS_INTRO') WHEN 'clan' THEN 'clan' WHEN 'inner_sphere' THEN 'inner_sphere' WHEN 'IS_INTRO' THEN 'inner_sphere' ELSE NULL END;IF tech_base IS NULL THEN RAISE EXCEPTION 'Choose Inner Sphere or Clan technology';END IF;
 engine_type:=coalesce(p_design->>'engine_type','standard');structure_type:=coalesce(p_design->>'structure_type','standard');armor_type:=coalesce(p_design->>'armor_type','standard');
 IF engine_type NOT IN ('standard','is_xl','clan_xl') OR structure_type NOT IN ('standard','is_endo_steel','clan_endo_steel') OR armor_type NOT IN ('standard','is_ferro_fibrous','clan_ferro_fibrous') THEN RAISE EXCEPTION 'Unsupported construction equipment';END IF;
 IF (tech_base='clan' AND (engine_type='is_xl' OR structure_type='is_endo_steel' OR armor_type='is_ferro_fibrous')) OR (tech_base='inner_sphere' AND (engine_type='clan_xl' OR structure_type='clan_endo_steel' OR armor_type='clan_ferro_fibrous')) THEN RAISE EXCEPTION 'Construction equipment must match the selected tech base';END IF;
 IF engine_type IN ('is_xl','clan_xl') THEN engine_multiplier:=.5;END IF;IF structure_type IN ('is_endo_steel','clan_endo_steel') THEN structure_multiplier:=.5;END IF;IF armor_type='is_ferro_fibrous' THEN armor_points_per_ton:=17.92;ELSIF armor_type='clan_ferro_fibrous' THEN armor_points_per_ton:=20;END IF;
 tonnage:=(p_design->>'tonnage')::int;walking:=(p_design->>'walking_mp')::int;jumping:=(p_design->>'jump_mp')::int;sinks:=(p_design->>'heat_sinks')::int;IF tonnage NOT BETWEEN 20 AND 100 OR tonnage%5<>0 THEN RAISE EXCEPTION 'Tonnage must be 20–100 in five-ton steps';END IF;
 rating:=tonnage*walking;engine_weight:=btech_standard_engine_weight(rating);IF walking<1 OR engine_weight IS NULL THEN RAISE EXCEPTION 'The engine rating must be between 5 and 400';END IF;engine_weight:=engine_weight*engine_multiplier;
 IF jumping<0 OR jumping>walking THEN RAISE EXCEPTION 'Jumping MP cannot exceed Walking MP';END IF;IF sinks<10 OR sinks>50 THEN RAISE EXCEPTION 'A BattleMech requires 10–50 heat sinks';END IF;
 armor:=coalesce(p_design->'armor','{}'::jsonb);weapons:=coalesce(p_design->'weapons','[]'::jsonb);ammo:=coalesce(p_design->'ammo','[]'::jsonb);IF jsonb_typeof(armor)<>'object' OR jsonb_typeof(weapons)<>'array' OR jsonb_typeof(ammo)<>'array' OR jsonb_array_length(weapons)>30 OR jsonb_array_length(ammo)>30 THEN RAISE EXCEPTION 'Invalid armor or equipment declaration';END IF;
 structure:=btech_custom_structure(tonnage);FOREACH loc IN ARRAY ARRAY['head','ct','ct_rear','lt','lt_rear','rt','rt_rear','la','ra','ll','rl'] LOOP value_int:=coalesce((armor->>loc)::int,0);IF value_int<0 THEN RAISE EXCEPTION 'Armor cannot be negative';END IF;armor_points:=armor_points+value_int;END LOOP;
 IF coalesce((armor->>'head')::int,0)>9 OR coalesce((armor->>'ct')::int,0)+coalesce((armor->>'ct_rear')::int,0)>2*(structure->>'ct')::int OR coalesce((armor->>'lt')::int,0)+coalesce((armor->>'lt_rear')::int,0)>2*(structure->>'lt')::int OR coalesce((armor->>'rt')::int,0)+coalesce((armor->>'rt_rear')::int,0)>2*(structure->>'rt')::int OR coalesce((armor->>'la')::int,0)>2*(structure->>'la')::int OR coalesce((armor->>'ra')::int,0)>2*(structure->>'ra')::int OR coalesce((armor->>'ll')::int,0)>2*(structure->>'ll')::int OR coalesce((armor->>'rl')::int,0)>2*(structure->>'rl')::int THEN RAISE EXCEPTION 'Armor exceeds a location maximum';END IF;
 FOR item IN SELECT value FROM jsonb_array_elements(weapons) value LOOP IF item->>'location' NOT IN ('head','ct','lt','rt','la','ra','ll','rl') THEN RAISE EXCEPTION 'A weapon has an invalid location';END IF;profile:=btech_custom_equipment(item->>'key');IF profile IS NULL OR (coalesce((profile->>'clan')::boolean,false) AND tech_base<>'clan') THEN RAISE EXCEPTION 'Unsupported custom-design weapon: %',item->>'key';END IF;equipment_weight:=equipment_weight+(profile->>'weight')::numeric;END LOOP;
 FOR item IN SELECT value FROM jsonb_array_elements(ammo) value LOOP IF item->>'location' NOT IN ('ct','lt','rt','la','ra','ll','rl') OR coalesce((item->>'bins')::int,0) NOT BETWEEN 1 AND 4 THEN RAISE EXCEPTION 'Each ammunition entry needs 1–4 bins in a legal location';END IF;ammo_profile:=btech_custom_ammo(item->>'type');IF ammo_profile IS NULL OR (coalesce((ammo_profile->>'clan')::boolean,false) AND tech_base<>'clan') THEN RAISE EXCEPTION 'Unsupported ammunition type: %',item->>'type';END IF;IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements(weapons) weapon WHERE btech_custom_equipment(weapon->>'key')->>'ammoType'=item->>'type') THEN RAISE EXCEPTION 'Ammunition was added without a matching launcher';END IF;ammo_weight:=ammo_weight+(item->>'bins')::int;END LOOP;
 IF EXISTS (SELECT 1 FROM jsonb_array_elements(weapons) weapon WHERE btech_custom_equipment(weapon->>'key') ? 'ammoType' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(ammo) bin WHERE bin->>'type'=btech_custom_equipment(weapon->>'key')->>'ammoType')) THEN RAISE EXCEPTION 'Every ammunition weapon needs at least one compatible bin';END IF;
 layout:=btech_build_custom_layout(p_design);structure_weight:=tonnage/10.0*structure_multiplier;gyro_weight:=ceil(rating/100.0);armor_weight:=ceil(armor_points/armor_points_per_ton);sink_weight:=greatest(0,sinks-10);jump_weight:=jumping*CASE WHEN tonnage<=55 THEN .5 WHEN tonnage<=85 THEN 1 ELSE 2 END;total_weight:=structure_weight+engine_weight+gyro_weight+3+armor_weight+equipment_weight+ammo_weight+sink_weight+jump_weight;IF total_weight>tonnage THEN RAISE EXCEPTION 'Design is overweight by % tons',total_weight-tonnage;END IF;
 RETURN jsonb_build_object('valid',true,'engine_rating',rating,'structure',structure,'critical_layout',layout,'armor_points',armor_points,'tech_base',tech_base,'construction',jsonb_build_object('engine',engine_type,'structure',structure_type,'armor',armor_type),'weights',jsonb_build_object('structure',structure_weight,'engine',engine_weight,'gyro',gyro_weight,'cockpit',3,'armor',armor_weight,'weapons',equipment_weight,'ammo',ammo_weight,'heat_sinks',sink_weight,'jump_jets',jump_weight,'total',total_weight,'remaining',tonnage-total_weight));
END $$;
REVOKE ALL ON FUNCTION public.btech_validate_custom_design(jsonb) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.save_btech_custom_design(p_catalogue_version text,p_design jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE design_id uuid:=gen_random_uuid();unit_id text;calculation jsonb;definition jsonb;layout jsonb;armor jsonb;structure jsonb;item jsonb;profile jsonb;ammo_profile jsonb;location text;slot_label text;slot_index int;mount_index int:=0;bin_index int:=0;counter int;bins int;
BEGIN
 IF auth.uid() IS NULL OR NOT EXISTS (SELECT 1 FROM btech_catalogue_releases WHERE version=p_catalogue_version) THEN RAISE EXCEPTION 'Sign in and choose an installed catalogue release';END IF;IF (SELECT count(*) FROM btech_custom_designs WHERE owner_id=auth.uid() AND NOT archived)>=50 THEN RAISE EXCEPTION 'A player may keep up to 50 active custom designs';END IF;
 calculation:=btech_validate_custom_design(p_design);layout:=calculation->'critical_layout';structure:=calculation->'structure';armor:=p_design->'armor';unit_id:='custom-'||replace(design_id::text,'-','');definition:=jsonb_build_object('id',unit_id,'chassis',btrim(p_design->>'name'),'variant',btrim(p_design->>'variant'),'mass',(p_design->>'tonnage')::int,'config','Biped','tech_base',CASE WHEN calculation->>'tech_base'='clan' THEN 'Clan' ELSE 'Inner Sphere' END,'era',3050,'movement',jsonb_build_object('walk',(p_design->>'walking_mp')::int,'run',ceil((p_design->>'walking_mp')::numeric*1.5)::int,'jump',(p_design->>'jump_mp')::int),'heat_sinks',(p_design->>'heat_sinks')::int,'heat_sink_type','Single','heat_sink_capacity',(p_design->>'heat_sinks')::int,'armor',armor,'structure',structure,'construction',calculation->'construction','supported_by_vtt',true,'custom_design',true,'custom_owner_id',auth.uid()::text);
 INSERT INTO btech_custom_designs(id,owner_id,catalogue_version,unit_id,name,design,calculation) VALUES(design_id,auth.uid(),p_catalogue_version,unit_id,btrim(p_design->>'name')||' '||btrim(p_design->>'variant'),p_design,calculation);INSERT INTO btech_catalogue_units(catalogue_version,unit_id,source_uuid,definition) VALUES(p_catalogue_version,unit_id,design_id::text,definition);
 FOR item IN SELECT value FROM jsonb_array_elements(p_design->'weapons') value LOOP profile:=btech_custom_equipment(item->>'key');location:=item->>'location';INSERT INTO btech_catalogue_mounts(catalogue_version,unit_id,mount_id,weapon_key,raw_name,location,definition) VALUES(p_catalogue_version,unit_id,(item->>'key')||':'||location||':'||mount_index,item->>'key',profile->>'name',location,(profile-ARRAY['name','weight','slots','label','clan']));mount_index:=mount_index+1;END LOOP;
 FOR item IN SELECT value FROM jsonb_array_elements(p_design->'ammo') value LOOP ammo_profile:=btech_custom_ammo(item->>'type');location:=item->>'location';bins:=(item->>'bins')::int;FOR counter IN 1..bins LOOP INSERT INTO btech_catalogue_ammo_bins(catalogue_version,unit_id,bin_id,ammo_type,raw_name,location,shots) VALUES(p_catalogue_version,unit_id,location||':'||bin_index,item->>'type',ammo_profile->>'name',location,(ammo_profile->>'shots')::int);bin_index:=bin_index+1;END LOOP;END LOOP;
 FOREACH location IN ARRAY ARRAY['head','ct','lt','rt','la','ra','ll','rl'] LOOP FOR slot_label,slot_index IN SELECT value#>>'{}',(ordinality-1)::int FROM jsonb_array_elements(layout->location) WITH ORDINALITY slot(value,ordinality) WHERE value<>'null'::jsonb LOOP INSERT INTO btech_catalogue_critical_slots(catalogue_version,unit_id,location,slot_index,label) VALUES(p_catalogue_version,unit_id,location,slot_index,slot_label);END LOOP;END LOOP;
 RETURN jsonb_build_object('id',design_id,'unit_id',unit_id,'catalogue_version',p_catalogue_version,'name',btrim(p_design->>'name')||' '||btrim(p_design->>'variant'),'calculation',calculation);
END $$;
REVOKE ALL ON FUNCTION public.save_btech_custom_design(text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.save_btech_custom_design(text,jsonb) TO authenticated;
